// Compile the editable SVG mode artwork to antialiased LVGL alpha masks.
// Run with Node and sharp; SHARP_MODULE can specify an installed module path.
const fs = require('fs');
const sharp = require(process.env.SHARP_MODULE || 'sharp');
(async () => {
 let out = '// Generated by tools/build_mode_assets.cjs; edit assets/modes/*.svg.\n#include <lvgl.h>\n';
 for (const name of ['weight', 'band', 'damper', 'isokinetic']) {
  const {data, info} = await sharp(`assets/modes/${name}.svg`, {density: 288})
   .resize(36, 36).ensureAlpha().raw().toBuffer({resolveWithObject:true});
  const bytes = Array.from({length: 36*36}, (_, i) => data[i*info.channels+info.channels-1]);
  out += `static const uint8_t ${name}_alpha[] = {\n`;
  for (let i=0;i<bytes.length;i+=24) out += bytes.slice(i,i+24).join(',')+',\n';
  out += `};\nconst lv_image_dsc_t mode_${name} = {\n.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,.w=36,.h=36,.stride=36},\n.data_size=sizeof(${name}_alpha),.data=${name}_alpha\n};\n`;
 }
 fs.writeFileSync('firmware/VoltraKnob/src/ui/mode_assets.c',out);
})();
